version: '3.8'

services:
  user_service:
    build:
      context: ./user_service
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://user:password@postgre_database:5432/user_db
    ports:
      - 5000:5000

  postgre_database:
      image: postgres:13
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: user_db
      ports:
        - 5432:5432
      volumes:
        - db_data:/var/lib/postgresql/data

volumes:
  db_data: